# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
user.agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) " +
  "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36


server:
  port: 8080
spring:
  datasource:
    platform: postgres
    username: user
    password: user
    url: jdbc:postgresql://localhost:5432/search-engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
    ddl-auto: create-drop
  liquibase:
    change-log: classpath:/liquibase/changelog.xml
    drop-first: true

